name: AustinBiz-Dot-Rocks - A b2b Vlogging Web Series
favicon: null
layout_spectrum: 0.943448159378022
typography_spectrum: 0.48118905909359455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9732453967444599
  lightness: 0.0771190645173192
  saturation: 0.44712021737359464
  rhythmicContrast: 0.11803267244249582
purpose: []
